server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.esupportail.esupnfccarteculture.postgres.PgFullTextDialect
        jdbc:
          lob:
            non_contextual_creation: true;
  messages:
    fallback-to-system-locale: false
    basename: "i18n/messages, i18n/application"
    use-code-as-default-message: true
    encoding: ISO_8859_1
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1d
          cache-public: true
      static-locations: classpath:/

logging:
  file:
    name: carte-culture.log
  level:
    root: info
    org.esupportail: info
    org.springframework: info